function Set-BuildNumber {
    <#
    .SYNOPSIS
    Set a custom build number

    .DESCRIPTION

    .EXAMPLE
    Set-TeamCityBuildNumber -BuildNumber '1.2.3_{build.number}'

    .EXAMPLE
    Set-TeamCityBuildNumber '1.2.3_beta1'

    .NOTES
    In the <new build number> value, you can use the {build.number} substitution
    to use the current build number automatically generated by TeamCity.

    .LINK
    https://www.jetbrains.com/help/teamcity/service-messages.html#Reporting+Build+Number
    #>
    [CmdletBinding()]
    [OutputType([System.Void])]
    param (
        [Parameter(Mandatory, Position = 0)]
        [string]
        # The build number
        $BuildNumber
    )
    if (IsRunningInTeamCity) {
        Write-Host "##teamcity[buildNumber '$(EscapeTeamCityBuildText $BuildNumber)']"
    } else {
        Write-Host "Set Build Number to '$BuildNumber'"
    }
}